# Generated by Django 3.1.5 on 2021-01-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210126_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usdt_balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=32),
        ),
    ]
