# Generated by Django 3.1.5 on 2021-01-27 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_usdt_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xfarm_balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=32),
        ),
        migrations.CreateModel(
            name='USDTWithdrawRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=32)),
                ('status', models.BooleanField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
