# Generated by Django 3.1.5 on 2021-01-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210127_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_bought',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=32),
        ),
    ]
