# Generated by Django 3.1.5 on 2021-01-27 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_total_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='usdtwithdrawrequest',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('unichain_purchase', 'Unichain purchase'), ('usdt_deposit', 'USDT deposit'), ('usdt_withdraw', 'USDT withdraw'), ('usdt_withdraw_reject', 'USDT withdraw reject'), ('xfarm_purchase', 'XFarm purchase'), ('referral_bonus', 'Referral bonus')], max_length=32)),
                ('usdt_change', models.DecimalField(decimal_places=6, default=0, max_digits=32)),
                ('xfarm_change', models.DecimalField(decimal_places=6, default=0, max_digits=32)),
                ('new_usdt_balance', models.DecimalField(decimal_places=6, default=0, max_digits=32)),
                ('new_xfarm_balance', models.DecimalField(decimal_places=6, default=0, max_digits=32)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
