# Generated by Django 3.1.5 on 2021-01-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210127_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
