# Generated by Django 3.1.5 on 2021-01-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_operationlog_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='type',
            field=models.CharField(choices=[('unichain_purchase', 'Unichain purchase'), ('usdt_deposit', 'USDT deposit'), ('usdt_withdraw', 'USDT withdraw'), ('usdt_withdraw_reject', 'USDT withdraw reject'), ('xfarm_exchange', 'XFarm exchange'), ('referral_bonus', 'Referral bonus')], max_length=32),
        ),
    ]
