# Generated by Django 3.1.5 on 2021-02-08 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210127_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=32)),
                ('length', models.PositiveIntegerField()),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='stake_bonus_balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=32),
        ),
        migrations.CreateModel(
            name='UserStakePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=32)),
                ('datetime', models.DateTimeField()),
                ('paid', models.BooleanField(default=False)),
                ('stake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.userstake')),
            ],
        ),
        migrations.AddField(
            model_name='userstake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakes', to=settings.AUTH_USER_MODEL),
        ),
    ]
