# Generated by Django 3.1.5 on 2021-02-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210208_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_stake_profit',
            field=models.DecimalField(decimal_places=2, default=-1, help_text='daily, -1 for global setting', max_digits=5),
        ),
    ]
