# Generated by Django 3.1.5 on 2021-02-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_user_custom_stake_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstake',
            name='finish',
            field=models.DateTimeField(null=True),
        ),
    ]
