# Generated by Django 3.1.5 on 2021-02-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_pendingstake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingstake',
            name='txid',
        ),
    ]
