# Generated by Django 3.1.5 on 2021-03-15 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_pendingstake_txid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(choices=[('usdt', 'Usdt'), ('curve', 'Curve'), ('sushi', 'Sushi'), ('farm', 'Farm')], max_length=8)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('finish', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=6, max_digits=32)),
                ('length', models.PositiveIntegerField()),
                ('extra_percent', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('extra_tokenx', models.BooleanField(default=False)),
                ('profit_percent', models.DecimalField(decimal_places=16, max_digits=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farming_deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
