# Generated by Django 3.1.5 on 2021-03-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_farmingdeposit_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmingdeposit',
            name='extra_tokenx',
        ),
        migrations.AddField(
            model_name='farmingdeposit',
            name='extra_tokenx',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=32, null=True),
        ),
        migrations.CreateModel(
            name='UserFarmingPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=32)),
                ('datetime', models.DateTimeField()),
                ('paid', models.BooleanField(default=False)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.farmingdeposit')),
            ],
        ),
    ]
