# Generated by Django 3.1.5 on 2021-03-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210316_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmingdeposit',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='userstake',
            options={'ordering': ('-pk',)},
        ),
        migrations.AddField(
            model_name='userfarmingpayment',
            name='tokenx_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=32),
            preserve_default=False,
        ),
    ]
