# Generated by Django 3.1.5 on 2021-03-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210316_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_farming',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=32),
        ),
    ]
