# Generated by Django 3.1.5 on 2021-03-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_user_total_farming'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfarmingpayment',
            name='extra_percent',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='farmingdeposit',
            name='extra_percent',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='farmingdeposit',
            name='extra_tokenx',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='farmingdeposit',
            name='profit_percent',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=32),
        ),
    ]
