# Generated by Django 3.1.5 on 2021-03-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210316_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfarmingpayment',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True),
        ),
    ]
