# Generated by Django 3.1.5 on 2021-03-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_userfarmingpayment_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmingdeposit',
            name='daily_percent',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=32),
        ),
    ]
