# Generated by Django 3.1.7 on 2021-03-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_usdtwithdrawrequest_erc20'),
    ]

    operations = [
        migrations.AddField(
            model_name='usdtwithdrawrequest',
            name='withdraw_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=32),
        ),
    ]
